version: "3.9"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 3
